set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/nurmdabd/.ciel/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/nurmdabd/.ciel/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/tiny-tpu-hardened"
set ::env(DESIGN_NAME) "tpu"
set ::env(VERILOG_FILES) "/openlane/designs/tiny-tpu-hardened/src/fixedpoint_simple.v /openlane/designs/tiny-tpu-hardened/src/control_unit.v /openlane/designs/tiny-tpu-hardened/src/loss_child.v /openlane/designs/tiny-tpu-hardened/src/loss_parent.v /openlane/designs/tiny-tpu-hardened/src/leaky_relu_derivative_child.v /openlane/designs/tiny-tpu-hardened/src/leaky_relu_derivative_parent.v /openlane/designs/tiny-tpu-hardened/src/leaky_relu_child.v /openlane/designs/tiny-tpu-hardened/src/leaky_relu_parent.v /openlane/designs/tiny-tpu-hardened/src/bias_child.v /openlane/designs/tiny-tpu-hardened/src/bias_parent.v /openlane/designs/tiny-tpu-hardened/src/vpu.v /openlane/designs/tiny-tpu-hardened/src/gradient_descent.v /openlane/designs/tiny-tpu-hardened/src/unified_buffer.v /openlane/designs/tiny-tpu-hardened/src/pe.v /openlane/designs/tiny-tpu-hardened/src/systolic.v /openlane/designs/tiny-tpu-hardened/src/tpu.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10.0"
set ::env(FP_CORE_UTIL) "10"
set ::env(PL_TARGET_DENSITY) "0.5"
set ::env(FP_PDN_MULTILAYER) "0"
set ::env(SYNTH_STRATEGY) "AREA 0"
set ::env(SYNTH_MAX_FANOUT) "6"
set ::env(SYNTH_READ_BLACKBOX_LIB) "1"
set ::env(SYNTH_NO_FLAT) "0"
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) "1"
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) "1"
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) "0"
set ::env(GLB_RESIZER_DESIGN_OPTIMIZATIONS) "0"
set ::env(GRT_REPAIR_ANTENNAS) "0"
set ::env(GRT_OVERFLOW_ITERS) "150"
set ::env(RUN_CVC) "0"
